version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:o21r73KZ8bwtz9dERd3Q9Kcw85lV7Gbvg3zT7mDvZws=
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=course_system
      - DB_USERNAME=postgres
      - DB_PASSWORD=acesse
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_DB=course_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=acesse
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
